services:
  mev-commit-bidder:
    build: 
      context: ./bidder
    environment:
      DOMAIN: ${DOMAIN}
      AUTO_DEPOSIT_VALUE: ${AUTO_DEPOSIT_VALUE}
      KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
      MEV_COMMIT_VALIDATOR_ROUTER_ADDR: ${VALIDATOR_OPT_IN_ROUTER_ADDRESS}
      MEV_COMMIT_BEACON_API_URL: ${MEV_COMMIT_BEACON_API_URL}
      MEV_COMMIT_L1_RPC_URL: ${MEV_COMMIT_L1_RPC_URL}
      MEV_COMMIT_NAT_ADDR: ${PUBLIC_IP}
      LOG_LEVEL: ${LOG_LEVEL}
    networks:
      - app-network
    ports:
      - "13522:13522" # p2p
      - "13523:13523" # http
      - "13524:13524" # rpc
    volumes:
      - ${KEYSTORE_PATH}:/keystore

  bot:
    build: 
      context: ./bot
    networks:
      - app-network
    env_file:
      - ./bot/.env
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - RPC_ENDPOINT=${RPC_ENDPOINT}
      - WS_ENDPOINT=${WS_ENDPOINT}
      - USE_PAYLOAD=${USE_PAYLOAD:-true}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - OFFSET=${OFFSET}
      - NUM_BLOB=${NUM_BLOB}
      - BID_AMOUNT=${BID_AMOUNT}
      - BID_AMOUNT_STD_DEV_PERCENTAGE=${BID_AMOUNT_STD_DEV_PERCENTAGE}
      - DEFAULT_TIMEOUT=${DEFAULT_TIMEOUT}
      - PRIORITY_FEE=${PRIORITY_FEE}

  datadog-agent:
    image: datadog/agent:latest
    container_name: datadog-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_TAGS=env:bidder-bot
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE=image:datadog/agent:*
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    depends_on:
      - bot 
      - mev-commit-bidder
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge

