services:
  mev-commit-bidder:
    build: 
      context: ./bidder
    environment:
      DOMAIN: ${DOMAIN}
      KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
      MEV_COMMIT_VALIDATOR_ROUTER_ADDR: ${VALIDATOR_OPT_IN_ROUTER_ADDRESS}
      MEV_COMMIT_BEACON_API_URL: ${BEACON_API_URL}
      MEV_COMMIT_L1_RPC_URL: ${L1_RPC_URL}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_FMT: ${LOG_FMT}
      MEV_COMMIT_VERSION: ${MEV_COMMIT_VERSION}
      MEV_COMMIT_PROPOSER_NOTIFY_OFFSET: ${MEV_COMMIT_PROPOSER_NOTIFY_OFFSET}
    networks:
      - app-network
    ports:
      - "13522:13522" # p2p
      - "13523:13523" # http
      - "13524:13524" # rpc
    volumes:
      - ${KEYSTORE_DIR}:/keystore
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/13524' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  bot:
    build: 
      context: ./bot
    networks:
      - app-network
    environment:
      - AUTO_DEPOSIT_AMOUNT=${AUTO_DEPOSIT_AMOUNT}
      - L1_RPC_URLS=${L1_RPC_URL}
      - BEACON_API_URLS=${BEACON_API_URL}
      - SETTLEMENT_RPC_URL=${SETTLEMENT_RPC_URL}
      - BIDDER_NODE_RPC_URL=mev-commit-bidder:13524
      - KEYSTORE_DIR=/keystore
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - BID_AMOUNT=${BID_AMOUNT}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FMT=${LOG_FMT}
    depends_on:
      mev-commit-bidder:
        condition: service_healthy
    volumes:
      - ${KEYSTORE_DIR}:/keystore

  datadog-agent:
    image: datadog/agent:latest
    container_name: datadog-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_TAGS=env:bidder-bot
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE=image:datadog/agent:*
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    depends_on:
      - bot 
      - mev-commit-bidder
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge
